CREATE DATABASE LapTrinhCity;
GO 

USE LapTrinhCity;
GO

CREATE TABLE HocVien
(
	maHV VARCHAR(10) PRIMARY KEY,
	tenHV NVARCHAR(100) NOT NULL,
	ngaySinh DATE NOT NULL,
	queQuan NVARCHAR(250) NOT NULL,
	soDT VARCHAR(15),
	eMail NVARCHAR(150)
);
GO

CREATE TABLE KhoaHoc
(
	maKH INT IDENTITY(1, 1) PRIMARY KEY,
	tenKH NVARCHAR(100) NOT NULL,
	ngayBatDau DATE NOT NULL,
	ngayKetThuc DATE NOT NULL,
	moTa NVARCHAR(250)
);
GO

CREATE TABLE DangKyKH
(
	maDK VARCHAR(10) PRIMARY KEY,
	maKH INT IDENTITY(1, 1) NOT NULL,
	maHV VARCHAR(10) NOT NULL,
	ngayDK DATE NOT NULL
	FOREIGN KEY(maKH) REFERENCES KhoaHoc(maKH),
	FOREIGN KEY(maHV) REFERENCES HocVien(maHV)
);
GO

CREATE TABLE BangDiem
(
	maDiem VARCHAR(10) PRIMARY KEY,
	maKH INT IDENTITY(1, 1) NOT NULL,
	maHV VARCHAR(10) NOT NULL,
	diem DECIMAL(2, 2)
	FOREIGN KEY(maKH) REFERENCES KhoaHoc(maKH),
	FOREIGN KEY(maHV) REFERENCES HocVien(maHV)
);
GO

CREATE TABLE DoanhThu
(
	maDoanhThu VARCHAR(5) PRIMARY KEY,
	maKH INT IDENTITY(1, 1) NOT NULL,
	soTien FLOAT NOT NULL,
	ngayNhanTien DATE
	FOREIGN KEY(maKH) REFERENCES KhoaHoc(maKH)
);
GO 